apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu
      command: [ "sleep", "1000" ]
      securityContext:
        capabilities:
          add: ["SYS_TIME"]
          drop: ["CHOWN"] 